Открывается и закрывается (часть 2)
htmlacademy-javascript/2209935-kekstagram-32 pull request #8
Opened 2024-07-18 10:13 UTC by SerIBuy

2024-07-18 14:33 UTC, craz3r requested changes

2024-07-18 14:33 UTC, craz3r commented on js/full-post-painting.js
> +let shownCommentsCount = 0;
Эта переменная выполняет ту же функцию что и переменная currentCommentsCount в замыкании -> логика дублируется

2024-07-18 14:33 UTC, craz3r commented on js/full-post-painting.js
> +let paintedCommentsPart;
Эта переменная не нужна если вы будете отрисовывать фрагмент внутри функции paintComments

2024-07-18 14:33 UTC, craz3r commented on js/full-post-painting.js
> +  commentsShownCount.textContent = shownCommentsCount;
Эта логика пересекается с такой же внутри функции paintComments

2024-07-23 13:51 UTC, SerIBuy commented on js/full-post-painting.js
> +let shownCommentsCount = 0;
shownCommentCount хранит количество отображенных комментариев, а currentCommentsCount показывает сколько комментариев отрисовывать на данном этапе(либо 5 либо 1-5) она необходима для метода splice. Можно обойтись и без currentCommentsCount, но тогда придется усложнить условие

2024-07-23 14:08 UTC, merged